Detect DMD continuation lines
When a template declared in another module fails to instantiate, DMD
produces errors such as:

lib.d(3,12): Error: undefined identifier 'invalid'
lib.d(8,12): Error: template instance lib.T!() error instantiating
src.d(3,1):        instantiated from here: U!()

Previously, Flycheck would only detect the first two lines as error
messages. However, since they both occur outside of the edited file,
this gives the impression that the edited file has no issues.

This patch detects continuation lines (such as the third line above) as
Flycheck errors with the "info" severity.