Handle `Unexpected end of file`
It's useless though since there is no line number to point to,
but should remove the `suspicious` waring from `flycheck` if there is no other errors

```
gfortran -fsyntax-only -fshow-column -fno-diagnostics-show-caret -fno-diagnostics-show-option -iquote /Volumes/CLOUD/JESSICA/KULITE_PIV/aqui24_040414-04/PROGRAM/ -std\=f95 -Wall -Wextra -I/usr/local/include -I. /Volumes/CLOUD/JESSICA/KULITE_PIV/aqui24_040414-04/PROGRAM/declarations2.f90
Error: Unexpected end of file in '/Volumes/CLOUD/JESSICA/KULITE_PIV/aqui24_040414-04/PROGRAM/declarations2.f90'
```

```
Suspicious state from syntax checker fortran-gfortran: Checker fortran-gfortran returned non-zero exit code 1, but no errors from output: Error: Unexpected end of file in '/var/folders/jy/nw9d_y3s5kz3jk2z0mg_pfm00000gn/T/flycheck4738SUw/declarations2.f90'
```