Properly locate include file in errors
gcc(e.g, 4.8.3, 4.9.1) sometimes seems to print included files
immediately after error. Here is a small testcase:

	// foo.cpp
	#include "foo.h"
	int main(int argc, char *argv[]) {
	    CHECK(Hi::b);
	    xx;
	}

	// foo.h
	namespace Hi { int a; };
	#define CHECK(arg) arg

gcc gives these errors:

	In file included from foo.cpp:1:0:
	foo.cpp: In function ‘int main(int, char**)’:
	foo.cpp:6:11: error: ‘b’ is not a member of ‘Hi’
	     CHECK(Hi::b);
		   ^
	foo.h:5:20: note: in definition of macro ‘CHECK’
	 #define CHECK(arg) arg
			    ^
	foo.cpp:8:5: error: ‘xx’ was not declared in this scope
	     xx;
             ^

This output folds incorrectly, causing Flycheck to fail.

Closes GH-783