Add the ability to group errors
The use case is mainly for some Rust errors, like lifetime and borrowing errors,
where multiple individual errors are actually part of the same "diagnostic" for
only one issue.  Here is an example of rustc output:

```
error[E0382]: use of moved value: `x`
 --> main.rs:9:7
  |
8 |   let y = x;          // note: x's lifetime ends here
  |       - value moved here
9 |   let z = x;          // error: can no longer move x
  |       ^ value used here after move
  |
  = note: move occurs because `x` has type `NonPOD`, which does not implement the `Copy` trait
```

In the JSON output parsed by Flycheck, this one diagnostic corresponds to three
errors and one note, all of which are turned into individual flycheck-error
objects.  Consequently, the relationship between these errors is lost, and this
could confuse users not familiar with these kinds of errors.

To preserve the relationship between errors, this commit adds a `group` property
to flycheck-error objects.  Checkers should use the same `group` value for
related errors.

This commits also adds a function to get related errors,
`flycheck-errors-from-group`.  This allows extensions to display related errors
as they see fit.